### ISSUE TITLE
Screen flashes: illegal option --p

### ISSUE THREAD

**Issue by wookayin** [mcchrish/nnn.vim#11]
Maybe related to #5, but not sure.

When executing `:Np`, the terminal just opens and immediately closes with an error.

```
nnn: illegal option -- p
usage: nnn [-b key] [-c N] [-e] [-i] [-l]
           [-S] [-v] [-h] [PATH]

The missing terminal file manager for X.
```

In https://github.com/mcchrish/nnn.vim/blob/master/plugin/nnn.vim#L55: `nnn -p` is used, but `nnn` has no such option. Maybe it has been removed in recent versions?

I was using `nnn 2.1` on macOS.

**Comment by mcchrish** [comment]
@wookayin hmm, seems like it.

cc @jarun 

I was using recent master version of nnn. But installing the one from homebrew doesn't have the `-p` option.

**Comment by mcchrish** [comment]
@jarun I wonder why it's a screenflash rather than logging an error in vim. Is passing illegal options/params in nnn exits non-zero code?

**Comment by wookayin** [comment]
> Is passing illegal options/params in nnn exits non-zero code?

Of course. Any CLI program is supposed to do this.

**Comment by jarun** [comment]
Fixed at https://github.com/jarun/nnn/commit/8cba83f43f7fca3f73698872da4e7f7c03faea38.

**Comment by wookayin** [comment]
I see, I had checked nnn wrong -- it was not giving an non-zero exit code :) Thanks for the help!

BTW why homebrew nnn doesn't have the `-p` option?

**Comment by jarun** [comment]
The vim support was added after v2.1 release. Please wait for v2.2.

**Comment by wookayin** [comment]
I wish there were some option that allows nnn to print the path (to stdout) upon keypress of <kbd>Enter</kbd> rather than directly opening it. I thought `-p` is the right guy for this. In such cases, the plugin integration can go very smooth. Actually it goes with [the Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy).

If it is not the case, one might think of having a keymap overriding <kbd>Enter</kbd> to make the nnn prints the selected files.

**Comment by mcchrish** [comment]
@jarun just sent an invite.

**Comment by jarun** [comment]
@wookayin I don't want to change the default behaviour of `nnn` and add a hook. I have explained this before.

- `nnn` has been extended to pick files without hurting any existing functionality
- The `Enter` key opens a file or directory in `nnn`. I would like to keep the experience same for users of `nnn`.
- There is a clear way of _selecting_ files in `nnn` and users should follow that
- The `Enter` key does not help in case of multiple selection

**Comment by jarun** [comment]
Guys, I reconsidered the request and found a way to meet the ends. Pressing Enter or ^M will now _pick_ the file and pressing right/l will open it (as in `nnn`).

**Comment by jarun** [comment]
I believe we can close this defect as @wookayin's problem is resolved.
