### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by kdheepak** [mcchrish/nnn.vim#112]
**Describe the bug**

The README currently has this code snippet:

https://github.com/mcchrish/nnn.vim/blob/c4c4d9531726c11892e32daa977c958ad47f7b97/README.md#L153-L163

However, `copy_to_clipboard` is not defined. Can you add an example for what this should be?

**Comment by mcchrish** [comment]
It's a function as seen here https://github.com/mcchrish/nnn.vim/releases/tag/v3.1
The example function writes the file paths into the clipboard.

I'll update the README to be more clear.
