### ISSUE TITLE
Error when using fzopen after changing directory

### ISSUE THREAD

**Issue by ram02z** [mcchrish/nnn.vim#133]
**To Reproduce**

1. Add fzopen as a plugin
2. Invoke `NNNPicker`
3. Change directory
4. Invoke `fzopen` and pick a file
4. Error shown and the file doesn't get picked

**Screenshots**

![image](https://user-images.githubusercontent.com/59267627/138560382-46ef0056-0372-4d7d-9f4b-135d084c9743.png)

**Environment:**

- Vim version: NVIM v0.6.0-dev+501-gcb15055c2
- Plugin manager: packer.nvim
- Plugin version: 1d5aed3
- Nnn version: 4.3

**Additional context**

The error doesn't occur for me if I don't change the directory that nnn.vim was invoked from.

nnn.vim config: https://github.com/ram02z/dotfiles/blob/6ee4aa967a18643a657f7d30cf4435fccb265f05/dot_config/nvim/plugin/50-plugins.lua#L321-L350

**Comment by jarun** [comment]
@mcchrish can you please take a look at it? Are you waiting for someone to pitch in?

**Comment by mcchrish** [comment]
@jarun I'm waiting for anyone to take a look.
PR is welcome and I can take a review.

**Comment by jarun** [comment]
In that case please respond to the defect with a note so someone else bothers to look into it.
What appears to be the problem? Do the error strings help?

**Comment by N-R-K** [comment]
This is probably a problem with `fzopen` plugin. I don't use it, so I'm not sure what's going on here. But seems to me that is the offending snippet.

```sh
# Check for picker mode
if [ "$3" ]; then
    if [ "$entry" ]; then
        if [ "-" = "$3" ]; then
            printf "%s\n" "$entry"
        else
            printf "%s\n" "$entry" > "$3"
        fi

        # Tell `nnn` to clear its internal selection
        printf "%s" "0p" > "$NNN_PIPE"
    fi

    exit 0
fi
```

**Comment by N-R-K** [comment]
Added the "help wanted" label so if anyone who's interested can take a look.

**Comment by jarun** [comment]
@N-R-K fzopen is working as expected in this block. This is a case of calling a picker plugin while `nnn` is started in picker mode. See `$3` in https://github.com/jarun/nnn/tree/master/plugins#access-level-of-plugins

So, if user is picking files using `fzopen()`, `nnn` should not pick files. The picker output file path is passed to the plugin (`-` if it's stdout) and the plugin will write picked files to it (`nnn` would skip writing to the output file).

**Comment by jarun** [comment]
@mizlan can you please have a look?

**Comment by N-R-K** [comment]
Can reproduce this with a dummy plugin with that block.
* Open NnnPicker
* Hover over a file and invoke the dummy plugin

```sh
#!/bin/sh

# Check for picker mode
entry="$1"
if [ "$3" ]; then
    if [ "$entry" ]; then
        if [ "-" = "$3" ]; then
            printf "%s\n" "$entry"
        else
            printf "%s\n" "$entry" > "$3"
        fi

        # Tell `nnn` to clear its internal selection
        printf "%s" "0p" > "$NNN_PIPE"
    fi

    exit 0
fi
```

**Comment by jarun** [comment]
In explorer mode, it just opens the plugin file.

**Comment by jarun** [comment]
That's with pick a plugin method... and expected as per current code.

**Comment by N-R-K** [comment]
Okay, I know what's going on. The plugin is printing only filename, not full path. So if you change directory it becomes a problem.

**Comment by jarun** [comment]
OK. I fixed the other issue with opening the plugin (instead of run) at https://github.com/jarun/nnn/commit/bdbd182c65cee58c2d09374a93a9ca3425e4ab7b.

**Comment by jarun** [comment]
@ram02z the fzopen plugin is fixed. Please confirm if the patch works for you.

**Comment by ram02z** [comment]
> @ram02z the fzopen plugin is fixed. Please confirm if the patch works for you.

The patch works great, thanks for the fix @N-R-K !
