### ISSUE TITLE
Explorer window does not close properly when multi tabs have their own opened explorer window

### ISSUE THREAD

**Issue by mcchrish** [mcchrish/nnn.vim#141]
Env:
- neovim
- zsh

Steps:
- I open an explorer in one tab then open another explorer in another tab.
- I then quit the explorer window in one tab then go to the other tab and quit the explorer window as well.
- I get a process exit 0 message instead of closing the window:
<img width="287" alt="Screen Shot 2021-11-01 at 4 37 05 PM" src="https://user-images.githubusercontent.com/7200153/139644641-54e5fc84-7eed-445e-bf9a-4415d6536d47.png">

We probably need to isolate more variables per tab to avoid shared states.

**Comment by N-R-K** [comment]
I believe I mentioned this issue somewhere in #128 . My hunch is that it has something to do with the `explorer_create_on_exit_callback` function.
