### ISSUE TITLE
Picker picks the wrong file if a directory with similar name exists

### ISSUE THREAD

**Issue by N-R-K** [mcchrish/nnn.vim#147]
## To Reproduce

1. Create the a dir/file `test/a` and a file named `test.file`

```
test
|   a
test.file
```

2. Open `test/a` in vim
3. Open NnnPicker
4. Go back a directory and try to pick `test.file`

## Expected behavior

It should pick `../test.file` but instead it tries to open `../file`

## Environment:

- Terminal: XTerm and ST
- Shell: zsh
- Vim version: vim 8.2
- Plugin version: master

**Comment by mcchrish** [comment]
I can replicate the issue.

Seems to be related to trimming the CWD from the file path.
