### ISSUE TITLE
When NnnExplorer is invoked via <Leader> key combination the first 10 entries are already tagged ????

### ISSUE THREAD

**Issue by ShiranC** [mcchrish/nnn.vim#154]
When NnnExplorer is invoked as a command ( ie. ":NnnExplorer" ), everything works as expected.

When NnnExplorer is invoked via a <leader> key combination (ie. nnoremap <silent> <leader>x :NnnExplorer<cr> ), the window opens up showing the directory structure but the first 10 entries are ALREADY tagged .

**Environment:**

- OS: macOS 10.15.7
- Terminal: iterm2 3.5.0beta4
- Shell: zsh 5.8.1 (x86_64-apple-darwin19.6.0)
- Vim version: Vim 8.2 (2019 Dec 12, compiled Feb 11 2022 21:13:35)
- Plugin manager: vim-plug
- Plugin version: @[mcchrish](https://github.com/mcchrish) mcchrish released this Dec 05, 2021
· [1 commit ](https://github.com/mcchrish/nnn.vim/compare/v3.6...master)to master since this release
[ v3.6](https://github.com/mcchrish/nnn.vim/tree/v3.6)  
 32d106a
- Nnn version: 4.4

**Comment by ShiranC** [comment]
correction to mapping of leader key 

nnoremap <silent> <leader>x :NnnExplorer<cr>

**Comment by ShiranC** [comment]
"nnoremap <silent> <leader>x :NnnExplorer<cr>"

**Comment by ShiranC** [comment]
```
nnoremap <silent> <leader>x :NnnExplorer<cr>        " Use nnn
```

**Comment by N-R-K** [comment]
> ```
> nnoremap <silent> <leader>x :NnnExplorer<cr>        " Use nnn
> ```

Can't reproduce. Works fine for me in both XTerm and ST using vim v8.2.
