### ISSUE TITLE
Error on opening nnn second time

### ISSUE THREAD

**Issue by jarun** [mcchrish/nnn.vim#17]
Steps:

While testing the plugin I noticed another issue:

1. opened a file in vim: `vim src/nnn.c`
2. Navigated up and used multi-select (^Y-^Y) to select 3 files
3. Pressed `q` (`nnn` opened a blank file here, probably the current issue we are discussing)
4. Pressed `\n` again

Seeing an error message highlighted in red. Please check.

**Comment by mcchrish** [comment]
After getting the error, what is the content when you run `:messages`?

**Comment by jarun** [comment]
I am not at my system now. Please check if you can reproduce. If not, I will share after i am back. 8 to 9 hrs.

**Comment by jarun** [comment]
My observations:

1. default beahviour: if I load vim without plugins:

    vim -u NONE src/nnn.c
and press `<leader> n`, I get the message:

    E35: No previous regular expression

2. With latest plugin, when I run the original test, I get the error:

    E486: Pattern not found: termux

3. If I close the file file from selection and press `<leader> n`, I get:

```
Error detected while processing function <SNR>38_callback:
line    2:
nnn exited with non-zero.
```

This is the best I can do about this. I believe you may have to reproduce yourself to fix this.

**Comment by jarun** [comment]
My leader key is `\`. I guess the default. Can you try with `\` as leader key?

**Comment by jarun** [comment]
OK, I also have the following in my `.vimrc`:

```
let g:nnn#set_default_mappings = 0 
nnoremap <leader>n :NnnPicker '%:p:h'<CR>
```

**Comment by jarun** [comment]
Any luck with this with the settings in .vimrc?

**Comment by jarun** [comment]
This seems to be fixed with latest master.
