### ISSUE TITLE
Unknown function term_start

### ISSUE THREAD

**Issue by smartmic** [mcchrish/nnn.vim#20]
I just installed the latest _nnn_ release and tried to get _nnn.vim_ working but `:NnnPicker` failed with this message:
![2018-11-30-10-19-06_scrot](https://user-images.githubusercontent.com/6379140/49280161-bf2e9c80-f489-11e8-871f-ccce635c303f.png)

**Comment by jarun** [comment]
vim plugin support is not available in the latest `nnn` release. Please wait for the next next release of try master (to get your hands dirty). ;)

**Comment by mcchrish** [comment]
@smartmic what's the version of your vim? This plugin uses the vim terminal feature so it means it needs a recent version of vim. Or use neovim.

**Comment by smartmic** [comment]
@mcchrish I use version 8.0 von vim:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)                            
Included patches: 1-197, 322, 377-378, 550, 703, 706-707

**Comment by smartmic** [comment]
@jarun thanks, I will do so.

**Comment by mcchrish** [comment]
@smartmic I think vim 8.0 adds async feature while 8.1 adds terminal.
