### ISSUE TITLE
Please confirm behaviour

### ISSUE THREAD

**Issue by jarun** [mcchrish/nnn.vim#21]
Noticing the following in vim status with master `nnn.vim`:

```
~/GitHub/nnn/CHANGELOG                                                                   1,1            Top
[src/nnn.c] /home/vaio/GitHub/nnn/nnn.1 /home/vaio/GitHub/nnn/Makefile /home/vaio/GitHub/nnn/LICENSE
```

Steps:

- I opened src/nnn.c
- Pressed `<leader> n`
- Selected the listed after `src/nnn.c` above
- Pressed Enter on CHANGELOG

CHANGELOG is opened and I see the above listing in status line with `:args`

Confirm if the above behaviour is correct.

Also, when I am closing I see only 2 files opened: CHANGELOG and LICENSE (neither src/nnn.c nor the other 2 files are there)

In my .vimrc I have the following mapping settings:

```
let g:nnn#set_default_mappings = 0 
nnoremap <leader>n :NnnPicker '%:p:h'<CR>
```

**Comment by mcchrish** [comment]
Seems right. But for me when pressing enter on CHANGELOG it's not the one displayed in the window but the first item that was selected in nnn. In this case `nnn.1` while the CHANGELOG is in the buffer list.

**Comment by jarun** [comment]
Thanks for confirming!
