### ISSUE TITLE
Minimum version 2.2?

### ISSUE THREAD

**Issue by esn89** [mcchrish/nnn.vim#24]
2.1 is the current version

**Comment by jarun** [comment]
Please wait till the next release of `nnn`.

**Comment by esn89** [comment]
So I can't use this plugin atm?

**Comment by mcchrish** [comment]
@esn89 you can use but we advice to build nnn from source for now. If you're in mac you can do `brew install nnn --HEAD` to install from latest master.

Also made note of this in the README:

>Work in Progress: For this to work as expected, you may need to build nnn from source as it needs some functionalities that are not yet released.

**Comment by jarun** [comment]
You can try `nnn` master.
