### ISSUE TITLE
Opening blank file second time

### ISSUE THREAD

**Issue by jarun** [mcchrish/nnn.vim#30]
Steps:

- `\n`, select file
- close file (`:q`)
- `\n` - instead on `nnn` selection view a blank file is opened

Environment:

vim v8.1
OS: Ubuntu 18.04 amd64
shell: bash and fish
nnn: master
nnn.vim: master

**Comment by jarun** [comment]
I see the following error at the bottom after third step:

```
!/bin/bash
nnn exited with -1
```

Both `nnn` and `nnn.vim` are latest master.

**Comment by jarun** [comment]
Please check if this issue is due to the exit code from the first instance of `nnn`.

**Comment by jarun** [comment]
Even without the override in .vimrc (https://github.com/mcchrish/nnn.vim/issues/30#issuecomment-450274949) I am seeing this issue.

**Comment by jarun** [comment]
@mcchrish any lead on this one?

**Comment by mcchrish** [comment]
@jarun seems to be related to #17 and actually experiencing it. It maybe a related issue. It has something to do with the `curwin: 1` option of vim and the default `nnn#layout` `enew`.

```vim
let s:term_buff = term_start([&shell, &shellcmdflag, l:cmd], {'curwin': 1, 'exit_cb': function(l:On_exit)})
```

The issue doesn't appear if it is set other than `enew`:

```vim
let g:nnn#layout = 'tabedit' " or others
```

So I think a work around for now is to change `g:nnn#layout` to `tabedit` as the default for vim (or `topleft 80vnew` seems to be more convenient). I'm not getting this issue in neovim.

However the above may not be related to your issue, as I unfortunately can't reproduce it. But can you try setting `g:nnn#layout` to something else if it fixes to you?

**Comment by jarun** [comment]
If I remove all my plugins, I see the following behaviour:

I have file1 open in vim. On opening file2 using nnn.vim, when I close it, vim quits. I was expecting file1 to be left open. Is this the expected behaviour?

**Comment by jarun** [comment]
If it's the correct behaviour, how do I keep the earlier file (file1) open?

**Comment by jarun** [comment]
OK. You can reproduce the issue with https://www.vim.org/scripts/script.php?script_id=159.

This retains the earlier buffer/file1 and then I see the issue.

Please check.

**Comment by mcchrish** [comment]
The plugin won't interfere with other buffers and always open a file as a new buffer. No buffers will be deleted. Running `:buffers` should list file1 and file2 in your use case.

**Comment by jarun** [comment]
Did you face the issue with the  plugin?

**Comment by jarun** [comment]
It should not error out the second time I press leader n and open nnn in picker mode.

maybe the problem is there is no file open in the buffer and the plugin can't determine the dir to open?

**Comment by mcchrish** [comment]
Didn't face the issue with the plugin. The only thing I can reproduce is https://github.com/mcchrish/nnn.vim/issues/30#issuecomment-450547557. The second time I press `<leader>n` it doesn't open the nnn window. But when I change the value of `g:nnn#layout` to something else and seems to work as expected.

**Comment by jarun** [comment]
@mcchrish please let me know if there's anything else I can help you with. I understand you can't reproduce but please try to analyze what's going wrong so we cn have a solution. The problem exists.

**Comment by jarun** [comment]
I see this scenario working properly on Linux subsystem for Windows with vim 8.1. I will update the vim version on my de and confirm it.

**Comment by jarun** [comment]
I am seeing this problem only when I use:

    vi file
and not when I use:

    vim file
I see that on my system (Ubuntu 18.04 amd64) `vi` is `/usr/bin/vi` which is a symlink to another file...

After adding the following to my shell's `rc` file I am not seeing this issue anymore:

    alias vi=vim

**Comment by jarun** [comment]
I update to v8.1 on Ubuntu. The issue still exists.

**Comment by mcchrish** [comment]
Thanks for the detailed information above. Sorry that the plugin is not working for you. I will be taking a look. I'd like to know more about some details of your system:

- OS: [e.g. macOS 10.14.2]
- Terminal: [e.g. iterm2 3.2.7beta2]
- Shell: [e.g. zsh 5.2.1, bash 4.1]
- Vim version: [e.g. neovim 0.3.2, vim 8.1 1-239]
- Plugin manager: [e.g. vim-plug, pathogen]
- Plugin version: master
- Nnn version: master

Do you see the issue with the nnn.vim plugin with or without minibufexpl installed?

**Comment by jarun** [comment]
With this version, when I close the picked file using `nnn`, vim quits. Is this expected? I would expect the earlier file to be opened instead of vim quitting.

**Comment by mcchrish** [comment]
I think that's expected with that version of minibufexpl. It seems to use only one window and doesn't override the `:q` command. To close a buffer without quitting vim run `:bdelete` or `:bd`.

**Comment by jarun** [comment]
OK. Thanks!

**Comment by jarun** [comment]
@mcchrish `nnn` v2.2 is released. If you think the plugin is stable enough please consider making the first release.
