### ISSUE TITLE
Opening Buffer Once

### ISSUE THREAD

**Issue by magicalbanana** [mcchrish/nnn.vim#34]
**Is your feature request related to a problem? Please describe.**

Is it possible to open the `nnn` window once? So let's say, I have it open already, open a file and then start `nnn` again, I expect that it reuses the same window.

**Comment by magicalbanana** [comment]
Actually, a simple solution would be if we open a file, we close the current buffer where `nnn` is open. How do we do that?

**Comment by mcchrish** [comment]
Sorry if I miss understood the feature request, do you mean the nnn window stays open when opening a file? Something like a nerdtree sidebar?

**Comment by jarun** [comment]
If you start with `nnn` (and not vim), the instance will be open in the background even if you spawn another instance of `nnn` as a picker. To achieve what you are looking for, all the `nnn` instances (including the first one) should be pickers. `nnn` picks and quits.
