### ISSUE TITLE
NnnPicker file select not working inside splits

### ISSUE THREAD

**Issue by thetarkus** [mcchrish/nnn.vim#35]
**Describe the bug**

Selecting a file from :NnnPicker inside of a split throws an error and then closes the split. 

**To Reproduce**

1. Open vim
2. Run command `:sp`
3. Navigate to new split (`<C-w>j`)
4. Run `:NnnPicker` (in new split)
3. In NnnPicker, press enter on file I want to edit
4. Pressing enter on the error message closes the split

```
Error detected while processing function <SNR>26_callback[7]..<SNR>26_eval_temp:
line   23:
E16: Invalid range: 2wincmd w
Press ENTER or type command to continue
```

**Expected behavior**

File should open in the split.

**Screenshots**

If applicable, add screenshots/gifs/videos to help explain your problem.

**Environment:**

- OS: Arch Linux
- Terminal: st 0.8.1
- Shell: bash 4.4
- Vim version: Nvim v0.3.2, Vim 8.1
- Plugin manager: vim-plug
- Plugin version: master
- Nnn version: 2.2

**Additional context**

I am looking to use NnnPicker as a split explorer rather than a project drawer, if that makes a difference. The idea is [explained here](http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/).

**Comment by mcchrish** [comment]
@thetarkus thanks for the bug report and suggestion. I actually like the concept and looks like the plugin is buggy with the use case. Just updated.

Also added a new behavior when nothing was selected when closing nnn, it switches backs to the last buffer of that window.
