### ISSUE TITLE
~/.nnncp file not generated on copy

### ISSUE THREAD

**Issue by rperryng** [mcchrish/nnn.vim#38]
**Describe the bug**

Hitting `<Space>` or `<C-k>` within the `nnn` buffer does not create the `DIR/.nnncp` file as described in the [docs for nnn](https://github.com/jarun/nnn#selection):

```
File paths are copied to the temporary file DIR/.nnncp, where DIR (by priority) is:

$HOME or,
$TMPDIR or,
/tmp
```

**To Reproduce**

Configuration:
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'mcchrish/nnn.vim'
call plug#end()
```

Steps to reproduce:

1. Open vim
2. Open nnn buffer (`\n`)
3. Press key `<C-k>` or `<Space>`
4. Directory is echoed at the bottom of the nnn UI to signify it was copied
5. Without exiting the `nnn` buffer, in another terminal run `cat ~/.nnncp`, `cat $TMPDIR/.nnncp`, `cat /tmp/.nnncp`
6. Observe that the file is not found

**Expected behavior**

`~/.nnncp` file should be populated with the selected directory/file.
This works as expected if I perform the action in `nnn` outside of vim

**Environment:**

- OS: macOS 10.14
- Terminal: iterm2 3.2.6
- Shell: zsh 5.5.1
- Neovim version: neovim 0.3.1
- Plugin manager: vim-plug
- Plugin version: master
- Nnn version: 2.2

**Additional context**

Alternatively, is there any way to interface with the selected entry in the NNN buffer?  Such as to copy its name into a vim register?

**Comment by mcchrish** [comment]
See commit: https://github.com/mcchrish/nnn.vim/commit/c27ef90e642f019961d3337c647c30f28c8aef04

Example: https://github.com/mcchrish/dotfiles/commit/f1a217371d4970f5cef23447662bbf6f2411ebee
