### ISSUE TITLE
Doesn't open in Vim

### ISSUE THREAD

**Issue by superDuperCyberTechno** [mcchrish/nnn.vim#40]
**Describe the bug**

Pressing `Enter` or `L` doesn't open the file in the current running Vim. It uses different applications depending on the file.

**To Reproduce**
1. Open Vim
2. Run command 'NnnPicker'
3. Open file (using `L` or `Enter`)

**Expected behavior**

Open the file for editing in the currently running (Neo)Vim instance

**Extra info**

This is probably not a bug in the software but rather in my brain. Please help.

**Comment by mcchrish** [comment]
You'd probably want to disable the `L` open on navigate feature, I personally find it unnatural to use. You can disable it by defining the env variable `let $NNN_RESTRICT_NAV_OPEN=1`.

For the `enter` however, do you have a way to reproduce it with a minimal vimrc?

**Comment by superDuperCyberTechno** [comment]
> For the `enter` however, do you have a way to reproduce it with a minimal vimrc?

Yep. Disabled everything except nnn.vim. Pressing enter on a source file simply opens it in a seperate application; PHP files are opened in `less`, JSON on the browser...  Bash variables `EDITOR` and `VISUAL` are set to `nano`

**Comment by mcchrish** [comment]
Do you have any other configuration set for nnn outside of vim? e.g. env variables in shell.

**Comment by superDuperCyberTechno** [comment]
Not for `nnn`, no. I just installed nnn via apt and plugged nnn.vim.

**Comment by superDuperCyberTechno** [comment]
Just realized I'm running nnn 1.9 and you specifically list 2.2 as a requirement...

**Comment by mcchrish** [comment]
Got it. I'll let you close the issue if you think there is no problem with the latest version.

**Comment by superDuperCyberTechno** [comment]
I'll just verify before closing.

**Comment by superDuperCyberTechno** [comment]
As of 2.3 it still opens in a seperate editor when using `L` if not disabled.

`Enter` works as expected.

**Comment by ldelossa** [comment]
@mcchrish 

just for my own knowledge is this now obsolete ? 

```
let $DISABLE_FILE_OPEN_ON_NAV=1
```

**Comment by Clish254** [comment]
I have this problem as well, when I open a file by pressing `L` it uses a different application to open the file. I want to disable `L` and just use `enter` but `let $DISABLE_FILE_OPEN_ON_NAV=1` doesn't seem to work anymore.

**Comment by mcchrish** [comment]
I believe it's changed to `-o` option now. See `man nnn`.
