### ISSUE TITLE
Environment variables within nnn#command doesn't work as expected

### ISSUE THREAD

**Issue by laggardkernel** [mcchrish/nnn.vim#44]
**Describe the bug**

Environment variables passed into `nnn#command` doesn't take effect.

```vim
let g:nnn#command = 'NNN_SHOW_HIDDEN=1 nnn -l' " light mode
nnoremap <leader>n :NnnPicker '%:p:h'<CR>
```

Hidden files are still not shown.

**Environment:**
- OS: macOS 10.13
- Shell: zsh 5.7.1
- Vim version: neovim v0.3.4
- Plugin manager: vim-plug
- Nnn version: 2.4

**Comment by mcchrish** [comment]
`NNN_SHOW_HIDDEN` seems to be removed in 2.4 https://github.com/jarun/nnn/blob/master/CHANGELOG#L16
