### ISSUE TITLE
Toggle Script

### ISSUE THREAD

**Issue by mckenziewagner** [mcchrish/nnn.vim#45]
**Is your feature request related to a problem? Please describe.**

Couldnt figure out a good way to toggle nnn in vim.

**Describe the solution you'd like**

```viml
let g:nnn#set_default_mappings=0
if argc() == 0
  au VimEnter * call nnn#pick('%:p:h', { 'edit': 'edit' })
endif
nnoremap <silent> q :call nnn#pick('%:p:h', { 'edit': 'vsplit', 'layout': { 'left': '~13%' } })<CR>
```

edit: better code ^^^

**Comment by mizlan** [comment]
I am confused by what you want. Where does anything get toggled in the code snippet you provide?

**Comment by jarun** [comment]
You cannot _toggle_ `nnn` in vim. If you want to close it use the usual `nnn` keys.

See https://github.com/jarun/nnn/wiki/Usage#keyboard-mouse

**Comment by mizlan** [comment]
I would mention, however, that one could probably implement some system for toggling the window containing the `nnn` terminal buffer. It would need to be re-positioned every time it is toggled back open though.
