### ISSUE TITLE
Support vim popup

### ISSUE THREAD

**Issue by mcchrish** [mcchrish/nnn.vim#46]
As the title says. Neovim and soon Vim will support floating window. Would be nice that the plugin can support it.

**Comment by jarun** [comment]
Awesome! Please let me know if we need to change anything in `nnn`.

**Comment by mcchrish** [comment]
Turns out nnn.vim can do this already. See example https://github.com/mcchrish/nnn.vim#layout

See also https://github.com/junegunn/fzf.vim/issues/664 since nnn.vim is pretty much implemented the same way.

**Comment by jarun** [comment]
Can you please add an example of how to use floating windiw with `vim`?

**Comment by jarun** [comment]
Also, is it possible to have a persistent window at the left with the "Or pass a dictionary with window size" example? When I open a file, the complete terminal is used by that file and the bar to the left isn't visible anymore.

**Comment by mcchrish** [comment]
Will probably leave this issue open to tackle on the vim feature. Not yet familiar as to how vim implements floating window.

>is it possible to have a persistent window at the left

Seems to be similar to what others request where the nnn window stays open in the left. It's probably possible to do this by interacting with nnn via stdout.

**Comment by jarun** [comment]
@mcchrish any update on this? This would be a very useful feature for nnn.vim users.

**Comment by jarun** [comment]
Thank you so much for this @mcchrish!

**Comment by jarun** [comment]
BTW, is this configurable? Can I still choose to use the floating window or the side pane?

**Comment by mcchrish** [comment]
Yes it's configurable. You can change the size, offset, border style and border color of the window.
```vim
let g:nnn#layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }
```
All the other types of layout still works including side pane.

**Comment by jarun** [comment]
@mcchrish Can we close this?
