### ISSUE TITLE
Part of the left is trimmed after upgrading nnn to 2.7

### ISSUE THREAD

**Issue by laggardkernel** [mcchrish/nnn.vim#47]
**Describe the bug**

When set layout to 'right' or a floating window, part of the left content is trimmed, which doesn't happen with nnn 2.6 but only on 2.7.

**To Reproduce**

```vim
let g:nnn#set_default_mappings = 0

nnoremap <leader>n :NnnPicker '%:p:h'<CR>

let g:nnn#layout = { 'right': '~20%' } " or right, up, down
```

Set layout as "left". Open vim, trigger the nnn window with `<leader>n`.

**Expected behavior**

Content in the nnn window should be left-aligned, and only right of the content is trimmed  when it's too long.

**Screenshots**

If applicable, add screenshots/gifs/videos to help explain your problem.

**Environment:**

- OS: macOS 10.13.6
- Terminal: kitty 0.14.6
- Shell: zsh 5.7.1
- Vim version: nvim 0.4.2
- Plugin manager: vim-plug
- Plugin version: master
- Nnn version: 2.7

**Comment by jarun** [comment]
@laggardkernel can you please share an image and probably give a count of how many columns are missing?

@mcchrish please let me know if you need anything from `nnn`.

**Comment by laggardkernel** [comment]
I did some more tests carefully. It turns out the problem is related to setting `scrolloff` and `sidescrolloff` from [vim-sensible](https://github.com/tpope/vim-sensible/blob/4a7159a30061b26aec9ac367823094e7fd0f6a5b/plugin/sensible.vim#L47-L52).

```vim
if !&scrolloff
  set scrolloff=1
endif
if !&sidescrolloff
  set sidescrolloff=5
endif
```

And only Neovim but not Vim is impacted. Removing these lines would fix the problem.

In fact, the problem could be reproduced with nnn 2.6 on Neovim as well. When resizing the window to a much smaller size with nnn 2.6, the left part of the content is trimmed too. 

Or another to put it, compared with nnn 2.6, the trimming is triggered even with a larger screen in nnn 2.7.
