### ISSUE TITLE
Not working! Screen flashes, nothing happens.

### ISSUE THREAD

**Issue by hatelove85911** [mcchrish/nnn.vim#5]
I'm using 

- terminal vim: version 8.1.72
- plugin manager: vim plug
- nnn: 2.1
- macOs: 10.14.1

When I type `:Np` in vim, screen flashes a bit, then nothing happens. There's no message in `:messages` commands

**Comment by mcchrish** [comment]
@hatelove85911 I can't seem to replicate it. However I've changed things a bit in vim to use the built-in terminal to open nnn (same as neovim now). Commit https://github.com/mcchrish/nnn.vim/commit/ff4c3f3919df4abf5c2ce2ea83c0d33fe8c32bb4. So the behavior have changed a bit. Can you please try the latest master?

**Comment by hatelove85911** [comment]
@mcchrish I'll try the new version tomorrow on my corporate PC and let you know the result.

**Comment by mcchrish** [comment]
closing this. It's a problem in nnn please wait for 2.2 release or build nnn from master.
