### ISSUE TITLE
nnn window isn't closed after picking

### ISSUE THREAD

**Issue by andoriyu** [mcchrish/nnn.vim#52]
When I use floating layout:
```
let g:nnn#layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }
```
Window floating view opens as expected, however after picking floating window stays up as empty buffer. Without window everything works as expected.

Steps to reproduce the behavior and with the **most minimal configuration**.
With only nnn.vim installed and additional configurations/plugins that helps reproduce the bug:

Use this layout:
```
let g:nnn#layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }
```

1. Open nnn as floating window
2. Pick file
3. [Window stays open](https://imgur.com/a/DHXWT6Q)

**Expected behavior**

I pick a file and window closes.

**Environment:**

- OS: FreeBSD nimble 12.1-RELEASE-p3 FreeBSD 12.1-RELEASE-p3 r359342 GENERIC  amd64
- Terminal: st
- Shell: zsh 5.8 (amd64-portbld-freebsd12.1)
- Vim version: 0.4.3
- Plugin manager:Plug
- Plugin version: master (today)
- Nnn version: 3.0

**Additional context**
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/libexec/ccache/cc -O2 -pipe -march=haswell -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -march=haswell -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wno-c11-extensions -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/wrkdirs/usr/ports/editors/neovim/work/.build/config -I/wrkdirs/usr/ports/editors/neovim/work/neovim-0.4.3/src -I/usr/local/include -I/usr/include -I/wrkdirs/usr/ports/editors/neovim/work/.build/src/nvim/auto -I/wrkdirs/usr/ports/editors/neovim/work/.build/include
Compiled by root@live-system-nimble-job-08

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info```

**Comment by mcchrish** [comment]
I somehow can't replicate the issue. However, I've some code related to handing the floating window https://github.com/mcchrish/nnn.vim/commit/3b7ebe12549e8ea9857c2bcfb8f553a0f535e02d where it closes the window on switching back.

Let me know if this change solved it for you.

**Comment by andoriyu** [comment]
@mcchrish it's working now. Thanks!
