### ISSUE TITLE
floating window layout error

### ISSUE THREAD

**Issue by step-** [mcchrish/nnn.vim#53]
**Describe the bug**

Pressing `<leader>n` with nnn.vim set in a floating window layout produces vim errors
```
Error detected while processing function nnn#pick:
line   19:
E948: Job still running (add ! to end the job)
```
and the following message in the floating window:
``` 
/bin/sh: -c option requires and argument
```

**To Reproduce**

Installed nnn 3.1, vim 8.2.534 Linux.
No `NNN_`* environment variables set.
In `.vimrc` (copied from README):
```vim
" Floating window (neovim latest and vim with patch 8.2.191)
let g:nnn#layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }
```

1. Open vim
2. Press `<leader>n`
3. See error

Thank you.

**Comment by mcchrish** [comment]
Was able to replicate it with minimal vimrc:

```vim
set nocompatible
set noswapfile

" Floating window (neovim latest and vim with patch 8.2.191)
let g:nnn#layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }

call plug#begin('~/.local/share/nvim/vendor')
Plug '~/vimming/nnn.vim'
call plug#end()
```

Have you set `hidden`? Unfortunately it is required for the plugin to work. See `:h hidden`

**Comment by jarun** [comment]
> it is required for the plugin to work

Please document this if not done already.

**Comment by step-** [comment]
@mcchrish Thank you for your reply. I can confirm that setting vim global option `hidden` in vim clears the issue.  However, I don't want to set `hidden` because it can lead to forgetting to save a modified file.  I concur with @jarun that it's enough to document the requirement, and let individual users decide about the trade-offs.
