### ISSUE TITLE
Error with vim version 8.2.579 

### ISSUE THREAD

**Issue by jarun** [mcchrish/nnn.vim#54]
Settings I have:

```
nnoremap <leader>n :NnnPicker '%:p:h'<CR>

" Floating window (neovim latest and vim with patch 8.2.191)
let g:nnn#layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }
```

Steps:

    vim somefile
    <leader>n

Messages I see:

```
Error detected while processing function <SNR>18_BufEnterHandler[15]..<SNR>18_AutoUpdate[44]..<SNR>18_Updat
eExplorer[27]..<SNR>18_SwitchWindow:
line   24:
E994: Not allowed in a popup window
E994: Not allowed in a popup window
E994: Not allowed in a popup window
E994: Not allowed in a popup window
E366: Not allowed to enter a popup window
```

**Comment by ldelossa** [comment]
seeing a similar issue after 
```Error detected while processing function nnn#pick:
line   19:
E863: Not allowed for a terminal in a popup window
"[No Name]" --No lines in buffer--
```

**Comment by mcchrish** [comment]
See https://github.com/mcchrish/nnn.vim/issues/59#issuecomment-633179825

**Comment by jarun** [comment]
@mcchrish I can confirm https://github.com/mcchrish/nnn.vim/tree/rewrite fixes the issue.

**Comment by jarun** [comment]
BTW, I checked in a little something yesternight you may be interested in: https://github.com/jarun/nnn/commit/56886922a62b39b43897988bdae289a47fc1026a

You can now pass the path to the current file when you start `nnn` and it will be hovered in `nnn`. Probably easier for user to track files instead of starting at the first file?

This will be available in the next release (due soon).

**Comment by jarun** [comment]
@mcchrish is there a way to tell the plugin to open the new file in vsplit or hsplit mode?
