### ISSUE TITLE
Colors are hard to read with termguicolors set

### ISSUE THREAD

**Issue by pauldiloreto** [mcchrish/nnn.vim#56]
**Describe the bug**
In order to use `coc-highlight` I am required to add `set termguicolors` in my vimrc/init.vim.

Unfortunately with this setting, nnn inside of vim uses colors that are very low contrast and difficuclt to read.

I realize that it is occurring because of this color setting I am adding, but it appears nnn inside of vim is the only thing being affected. Any advise would be appreciated.

**To Reproduce**

1. Add `set termguicolors`
2. Open Nnn picker in VIm

**Expected behavior**

Same colors as nnn outside of vim.

**Screenshots**

![Screen Shot 2020-04-29 at 1 04 32 AM](https://user-images.githubusercontent.com/18269267/80573821-929bee80-89b5-11ea-9f37-1cd7de34c5c2.png)
![Screen Shot 2020-04-29 at 1 04 46 AM](https://user-images.githubusercontent.com/18269267/80573832-962f7580-89b5-11ea-87bf-45177bf0b566.png)

**Environment:**

- OS: macOS 10.15.4
- Terminal: iTerm2
- Shell: zsh 5.8
- Vim version: NVIM v0.4.3
- Plugin manager: vim-plug
- Plugin version: master
- Nnn version: 3.0

**Comment by mcchrish** [comment]
Does your colorscheme support terminal colors for neovim? Usually the colorscheme should have set this variables https://github.com/neovim/neovim/issues/2897#issuecomment-115464516 or you can set them yourself if you want to customize it.

**Comment by pauldiloreto** [comment]
@mcchrish Thank you for your comment & providing this excellent plugin.

Looks like that was it, my colorscheme simply did not support terminal colors.
Setting the variables according to that comment did the trick. Thank you!
