### ISSUE TITLE
script errors on file open

### ISSUE THREAD

**Issue by PartyLich** [mcchrish/nnn.vim#58]
**Describe the bug**
When opening a file, I receive the following error message in nvim
```
Error detected while processing function <SNR>48_callback[6]..<SNR>48_eval_temp_file[4]..<SNR>48_switch_back:                               
line   13:
E716: Key not present in Dictionary: window) == v:t_dict
Press ENTER or type command to continue
Error detected while processing function <SNR>48_callback[6]..<SNR>48_eval_temp_file[4]..<SNR>48_switch_back:
line   13:
E116: Invalid arguments for function type
Press ENTER or type command to continue
Error detected while processing function <SNR>48_callback[6]..<SNR>48_eval_temp_file[4]..<SNR>48_switch_back:
line   13:
E15: Invalid expression: type(l:layout) == v:t_dict && type(l:layout.window) == v:t_dict
Press ENTER or type command to continue
```
The file opens as expected and the nnn window closes once I've ENTERed my way through the errors. So it more or less works, it's just a bit inconvenient.

**To Reproduce**

minimal neovim config:
```
call plug#begin()
  " nnn filemanager integration
  Plug 'mcchrish/nnn.vim'
call plug#end()

" Or pass a dictionary with window size
let g:nnn#layout = { 'left': '~20%' }
```

1. Open nvim
2. open nnn as filepicker with `<leader>n`
3. Locate a file and hit `ENTER` to open

**Expected behavior**

nnn is displayed in a vertical split to the left, 20% of screen width. The file opens, no errors displayed (specifically none occurring, not just suppressed :) ).  

I'd personally rather have the filepicker window remain *open* afterward, but that's either a config i havent found or a separate feature request.

**Screenshots**

n/a

**Environment:**

- OS: Ubuntu 18.04.4 LTS x86_64
   wm: i3
- Terminal:  gnome-terminal
- Shell: bash 4.4.20
- Vim version: 
  NVIM v0.5.0-517-gf2894bffb
  Build type: RelWithDebInfo
  LuaJIT 2.1.0-beta3
- Plugin manager: vim-plug
- Plugin version: master
- Nnn version: 2.7

**Comment by mcchrish** [comment]
Can you try latest master? I pushed a commit that might fix it. https://github.com/mcchrish/nnn.vim/commit/e945cf3b52c3af2f19e9dec91e5d44af75a9a88b

**Comment by PartyLich** [comment]
Works! Thank you for the rapid response.
