### ISSUE TITLE
error in switch_back function

### ISSUE THREAD

**Issue by ldelossa** [mcchrish/nnn.vim#59]
**Describe the bug**

When navigating to files in nnn-vim I receive an error in the switch_back method.
```
"src/libcrun/cgroup.c" line 52 of 2602 --1%-- col 1
Error detected while processing function <SNR>76_callback[6]..<SNR>76_eval_temp_file[4]..<SNR>76_switch_back[13]..<SNR>76_present:
line    2:
E896: Argument of get() must be a List, Dictionary or Blob
```

Seems like this method is receiving the wrong data type.

**To Reproduce**
I am using vimx from the default fedora repositories. 

```
❯ vimx --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 18 2020 00:00:00)
Included patches: 1-789
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
```
nnn-vim (master)
nnn v3.0

Steps to reproduce the behavior and with the **most minimal configuration**.
With only nnn.vim installed and additional configurations/plugins that helps reproduce the bug:

1. Open vim
2. Run command '....'
3. Press key '....'

**Expected behavior**

Opening a file does not produce error.

**Environment:**

- OS: Fedora 32
- Terminal: tilix
- Shell: zsh
- Vim version: vimx 8 (fedora repos)
- Plugin manager: vim-plug
- Plugin version: master
- Nnn version: 3.0

**Comment by ldelossa** [comment]
short circuiting the "present" function removes the bug. I know this is not the right thing to do, but narrows down the cause. 

```
function! s:present(dict, ...)
    return 0
    for key in a:000
        if !empty(get(a:dict, key, ''))
            return 1
        endif
    endfor
    return 0
endfunction
```

**Comment by alexk7110** [comment]
I was just looking for this, opening of the files occurs anyway so `return 0` is a nice one for now.

**Comment by ldelossa** [comment]
yes, also just changing the dictionary to something like:

```
let g:nnn#layout = { 'left': '~20%' }
```

does the trick.

**Comment by mcchrish** [comment]
I pushed some commit in master that could fix it. https://github.com/mcchrish/nnn.vim/commit/78e0a0fbfd970be6f3b9174daf495356e2b02d89

Can you take a look?

Thank you for reporting.

**Comment by jarun** [comment]
@mcchrish can you please take a look at https://github.com/mcchrish/nnn.vim/issues/54?

**Comment by ldelossa** [comment]
@mcchrish issue where providing no layout dictionary is fixed in master.
However the 'window' dictionary which enables the popup window version of nnn-vim is still broken.

**Comment by mcchrish** [comment]
Can you try using the branch https://github.com/mcchrish/nnn.vim/tree/rewrite

```vim
Plug 'mcchrish/nnn.vim', { 'branch': 'rewrite' }
```

Somehow vim must have change how popups work with terminal in latest patches. So I have to rewrite the whole approach of handling the windows.

**Comment by ldelossa** [comment]
@mcchrish your rewrite branch fixes all issues.
