### ISSUE TITLE
Show git changes

### ISSUE THREAD

**Issue by amitlevy21** [mcchrish/nnn.vim#64]
**Is your feature request related to a problem? Please describe.**

When I change a file in vim, it would be nice if I could see which files were lastly modified since last commit.

**Describe the solution you'd like**

Basicly i'm looking for something like [this](https://github.com/Xuyuanp/nerdtree-git-plugin) for nnn.vim.

**Describe alternatives you've considered**

I'm not sure what else I can do besides asking nicely from the developers to implement this.

Thank you for considering this.

**Comment by mcchrish** [comment]
That's a cool feature. However it might be better to ask this feature in the main nnn repo https://github.com/jarun/nnn
