### ISSUE TITLE
Search option request

### ISSUE THREAD

**Issue by VNMNTN** [mcchrish/nnn.vim#65]
Hello! Are you not planning option "search_on_open" (lusty file system explorer like). Navigation with arrows too loong... Thanks!

**Comment by jarun** [comment]
Hello! Did you try the plugin `fzopen`?

**Comment by ozkanonur** [comment]
![2021-05-17_20-39](https://user-images.githubusercontent.com/39852038/118532839-11460400-b750-11eb-91a7-805b19e06c2a.png)

As in the screenshot above, that is what happens to me when I use fzopen plugin. When I press ENTER on the result, the plugin opens the file inside the search window.

**Comment by jarun** [comment]
@ozkanonur This is fixed at https://github.com/jarun/nnn/commit/cbc458763052f7ac9612915202b1c25a24dcef87.

You have to take nnn from master and the plugin fzopen from master (preferably, manually).
