### ISSUE TITLE
Current version breaks on vim 8.1 on Debian

### ISSUE THREAD

**Issue by linuxclowns** [mcchrish/nnn.vim#66]
I updated from v1.6 (5a5c992) to the most recent release and nnn.vim breaks when it's called with the following error:

`Error detected while processing function nnn#pick[12]..<SNR>27_build_window[3]..<SNR>27_create_term_buf:
line    9:
E121: Undefined variable: #
E116: Invalid arguments for function term_start([&shell, &shellcmdflag, a:opts.cmd], #{  curwin: l:curwin, hidden: l:hidden,
exit_cb: l:Exit_cb })
line   17:
E121: Undefined variable: l:tbuf
`

Switching to the previous release solves the problem. BugFix please?

**Comment by mcchrish** [comment]
@linuxclowns still an issue with the latest version?

**Comment by linuxclowns** [comment]
Afraid so...

`Error detected while processing function nnn#pick[12]..<SNR>30_build_window[3]..<SNR>30_create_term_buf:
line    9:
E121: Undefined variable: #
E116: Invalid arguments for function term_start([&shell, &shellcmdflag, a:opts.cmd], #{  curwin: l:curwin, hidden: l:hidden,
exit_cb: l:Exit_cb })
line   17:
E121: Undefined variable: l:tbuf
`

**Comment by mcchrish** [comment]
Can you send a detailed report of your env? Similar to the issue template https://github.com/mcchrish/nnn.vim/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by linuxclowns** [comment]
Sure thing:

OS: Debian 10
Terminal: st 0.8.2
Vim version: 8.1.1401
Plugin Manager: vim-plug
Plugin Version: v1.6 (working), master (not working)
Nnn version v3.4

**Comment by jarun** [comment]
@mizlan does the following error and the linked commit give any hints here?

```
Error detected while processing function nnn#pick[12]..<SNR>27_build_window[3]..<SNR>27_create_term_buf: line 9: E121: Undefined variable: # E116: Invalid arguments for function term_start([&shell, &shellcmdflag, a:opts.cmd], #{ curwin: l:curwin, hidden: l:hidden, exit_cb: l:Exit_cb }) line 17: E121: Undefined variable: l:tbuf
```

**Comment by mizlan** [comment]
@linuxclowns if possible may I get a minimal vimrc that produces this error?

**Comment by jarun** [comment]
Closing this as there's no response and new versions are available.
Please confirm with the latest and get back with the requested details if you still see the issue.
