### ISSUE TITLE
"E79: Cannot expand wildcards" when using `NnnPicker '%:p:h'` and fish shell

### ISSUE THREAD

**Issue by asgeo1** [mcchrish/nnn.vim#72]
**Describe the bug**

I'm getting a "E79: Cannot expand wildcards" error message when using the `NnnPicker '%:p:h'` command.

**To Reproduce**

1. Use fish shell

        fish --version
        fish, version 3.1.2

        echo $SHELL
        /usr/local/bin/fish

        # .vimrc
        set shell=/usr/local/bin/fish

1. Use suggested custom mapping configuration

        " Disable default mappings
        let g:nnn#set_default_mappings = 0

        " Start nnn in the current file's directory
        nnoremap <leader>n :NnnPicker '%:p:h'<CR>

2. Trigger `,n`

3. Get error message:

        :NnnPicker '%:p:h'
        E79: Cannot expand wildcards

        Press ENTER or type command to continue

    (after pressing ENTER, it does show the nnn output for the directory as expected)

**Expected behavior**

It should work without the error message

**Environment:**

- OS: macOS 10.15.6 
- Terminal: kitty 0.18.3
- Shell: fish 3.1.2
- Vim version: neovim 0.4.3
- Plugin manager: vim-plug
- Plugin version: 13b605c
- Nnn version: 3.4

**Additional context**

It may not be an issue with this plugin, perhaps it's something to do with vim + fish... not sure.

**Comment by asgeo1** [comment]
The problem is with the suggested mapping in the README.

If I change the mapping to `nnoremap <leader>n :NnnPicker %:p:h<CR>` (i.e. without the single-quotes) it works fine with no error.

**Comment by jarun** [comment]
@asgeo1 Please raise a PR to fix the same and I'll pull it in.

**Comment by jarun** [comment]
Ahh, OK. I updated the doc with fish-specific note. Please ignore the above request.
