### ISSUE TITLE
7601: No such file or directory                                                            

### ISSUE THREAD

**Issue by ldelossa** [mcchrish/nnn.vim#78]
**Describe the bug**

Using nnn.vim v2.0 or later I receive the following error message when opening nnn from vim. 

7601: No such file or directory

Downgrading to v1.8 fixes this issue.

**To Reproduce**

Steps to reproduce the behavior and with the **most minimal configuration**.
With only nnn.vim installed and additional configurations/plugins that helps reproduce the bug:

1. open vim
2. use your nnn shorcut to open the nnn buffer

**Expected behavior**

The nnn buffer to open.

**Screenshots**

If applicable, add screenshots/gifs/videos to help explain your problem.

**Environment:**

- OS: Fedora 32
- Terminal: Tilix
- Shell: zsh 5.2.1
- Vim version:  vim 8.1 1-239
- Plugin manager: vim-plug
- Plugin version: [e.g. master, v2.0, v2.1]
- Nnn version: 3.4

**Additional context**

**Comment by mcchrish** [comment]
>use your nnn shorcut to open the nnn buffer

Please provide a minimal vimrc that reproduces the bug.

**Comment by mcchrish** [comment]
Maybe related to the breaking change? https://github.com/mcchrish/nnn.vim/releases/tag/v2.1

I updated the notes to be more descriptive.

**Comment by infinite-ops** [comment]
I had the same issue, @mcchrish is correct https://github.com/mcchrish/nnn.vim/releases/tag/v2.1 removing quotes fixed the issue for me.

**Comment by ldelossa** [comment]
Thanks i totally missed that. Fixed!
