### ISSUE TITLE
When in nnn map l to open in current

### ISSUE THREAD

**Issue by divramod** [mcchrish/nnn.vim#79]
Hey, 

thx for port to vim!

Is it somehow possible to map l to open the file under the cursor in the current window?

**Comment by mcchrish** [comment]
Since nnn is running in a terminal buffer it's possible to remap any input key:
```vim
autocmd! FileType nnn tnoremap <buffer> i <cr>
```
Mapping `i` to `<cr>` since enter mean to open the current file under the cursor.

**Comment by idmyn** [comment]
I might be missing something (I'm a vim newbie) but this remap also triggers if the key is pressed when naming a file, which is pretty annoying. Is there a way around that? Thanks for the plugin btw!

**Comment by mcchrish** [comment]
@idmyn I'm not sure there's a workaround. The neovim instance does not know the state of the nnn instance is in.
It's probably recommended to only using mappings with modifier to avoid it. e.g `<c-i>`.
