### ISSUE TITLE
Improving nnn.vim readability

### ISSUE THREAD

**Issue by ldelossa** [mcchrish/nnn.vim#80]
**Describe the bug**

Not quite a bug, but I'm at a road block. I cannot find any highlight groups being applied to a executable file in my nnn.vim terminal window. I use my own custom theme, but not quite show to to alter the colour of an executable file.

**To Reproduce**

Utilize my theme: github.com/ldelossa/vimdark and open an nnn window. 

**Expected behavior**

The ability to change the colors inside nnn.vim's window. 

**Screenshots**

![image](https://user-images.githubusercontent.com/5642902/100674997-21019580-3334-11eb-84ea-b5e976032d90.png)

**Environment:**

- OS: Fedora
- Terminal: Tilix
- Shell: zsh 5.2.1
- Vim version: vim 8
- Plugin manager: vim-plug
- Plugin version: master
- Nnn version: 3.4

**Comment by ldelossa** [comment]
![image](https://user-images.githubusercontent.com/5642902/100675331-c288e700-3334-11eb-90db-6fa644ce9acd.png)


as you can see from screen shot, the colors in vim8 term are readable, but nnn window is not.

**Comment by mcchrish** [comment]
Does it fix the colors if you pass `-C` to the nnn command? i.e. `nnn -C`

**Comment by ldelossa** [comment]
![image](https://user-images.githubusercontent.com/5642902/100682853-fe2bad00-3344-11eb-8480-dcbd044161e4.png)

Left is a normal "ls -la" and right is "nnn -C" so yes, but also removes other colors.

**Comment by ldelossa** [comment]
discovered "NNN_FCOLORS" thank you for your help! closing as I see a way to fix this issue.

**Comment by mcchrish** [comment]
Ok, good. It would be nice if nnn follows `LSCOLORS` by default.

**Comment by ldelossa** [comment]
I do agree, using LS_COLORS would be helpful.
