### ISSUE TITLE
Get error "zsh:1 command not found: nnn"

### ISSUE THREAD

**Issue by alexya** [mcchrish/nnn.vim#84]
**Describe the bug**

Get error "zsh:1 command not found: nnn" when inputting ":Np" to open the nnn picker.

**To Reproduce**

Steps to reproduce the behavior and with the **most minimal configuration**.
With only nnn.vim installed and additional configurations/plugins that helps reproduce the bug:

1. Open neovim
2. Run command ':Np' to open the nnn picker
3. Press key 'Enter'
4. See error as following:

```
zsh:1: command not found: nnn

[Process exited 127]
```

**Expected behavior**

open the picker successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/2831220/108591164-4685c480-73a2-11eb-8af4-ad3318cd186e.png)

**Environment:**

- OS: [e.g. macOS 10.15.6]
- Terminal: mac default
- Shell: zsh 5.7.1 (x86_64-apple-darwin19.0)
- Vim version: neovim 0.4.4
- Plugin manager: vim-plug
- Plugin version:  master
- Nnn version: default

**Additional context**

**Comment by mcchrish** [comment]
Can you confirm nnn is installed?
You can also manually set the nnn binary/command via `g:nnn#command` e.g.:
```vim
let g:nnn#command = '/usr/local/bin/nnn'
```

**Comment by alexya** [comment]
Yes. I didn't install the nnn. after I installed it. it is fixed. thx a lot.
