### ISSUE TITLE
File opening in nnn window instead of vim main window

### ISSUE THREAD

**Issue by medwatt** [mcchrish/nnn.vim#85]
I am using the [`fzopen`](https://github.com/jarun/nnn/blob/master/plugins/fzopen) plugin which allows you to use fzf to quickly locate a file. The only problem is that when you press ENTER on the found file, it opens it inside the floating window instead of the main window. Is there a way to fix this issue ?

**Comment by mcchrish** [comment]
Duplicate https://github.com/mcchrish/nnn.vim/issues/82
