### ISSUE TITLE
Opening a file from startup page does not open in main window

### ISSUE THREAD

**Issue by medwatt** [mcchrish/nnn.vim#87]
I use the [startify](https://github.com/mhinz/vim-startify) plugin as my startup page. If I open a file via nnn from the startup page, it does not open in the main window, but opens inside the small window designated for it.

This is my config:

```vim
let g:nnn#layout = { 'left': '~20%' }
let g:nnn#statusline = 0

let g:nnn#set_default_mappings = 0
let g:nnn#command = 'nnn -goQ'


autocmd! FileType nnn
autocmd  FileType nnn set mouse=
  \| autocmd BufLeave <buffer> set mouse=a

nnoremap <silent> <leader>n :NnnPicker %:p:h<CR>

let g:nnn#action = {
      \ '<c-t>': 'tab split',
      \ '<c-x>': 'split',
      \ '<c-v>': 'vsplit' }
```

![](https://i.imgur.com/NOReSWP.gif)

**Comment by mizlan** [comment]
There are some related issues with vim-startify, such as not cleaning up the extra tab created when `g:nnn#layout = 'tabnew'`, but all these issues seem to be fixed if the corresponding window is deleted during cleanup.

**Comment by jarun** [comment]
Many thanks for checking this out!
